/*******************************************************************************
 * Copyright (C) 2016-2020 Christopher Ali
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 *  If you have any questions about this project, you can visit
 *  the project's GitHub repository at: http://github.com/chris-ali/j6dof-flight-sim/
 ******************************************************************************/
package com.chrisali.javaflightsim.simulation.setup;

/**
 *	Provides the keys for the initialConditions EnumMap generated by {@link IntegrationSetup}
 */
public enum InitialConditions {
	INITU 	  ("initU"),
	INITV 	  ("initV"),
	INITW 	  ("initW"),
	INITN 	  ("initN"),
	INITE 	  ("initE"),
	INITD 	  ("initD"),
	INITPHI   ("initPhi"),
	INITTHETA ("initTheta"),
	INITPSI   ("initPsi"),
	INITP 	  ("initP"),
	INITQ 	  ("initQ"),
	INITR 	  ("initR"),
	INITLAT   ("initLat"),
	INITLON   ("initLon");
	
	private final String initialCondition;
	
	InitialConditions(String initialCondition) {this.initialCondition = initialCondition;}
	
	public String toString() {return initialCondition;}
}
