package com.chrisali.javaflightsim.simulation.setup;

/**
 *	Provides the keys for the initialConditions EnumMap generated by {@link IntegrationSetup}
 */
public enum InitialConditions {
	INITU 	  ("initU"),
	INITV 	  ("initV"),
	INITW 	  ("initW"),
	INITN 	  ("initN"),
	INITE 	  ("initE"),
	INITD 	  ("initD"),
	INITPHI   ("initPhi"),
	INITTHETA ("initTheta"),
	INITPSI   ("initPsi"),
	INITP 	  ("initP"),
	INITQ 	  ("initQ"),
	INITR 	  ("initR"),
	INITLAT   ("initLat"),
	INITLON   ("initLon");
	
	private final String initialCondition;
	
	InitialConditions(String initialCondition) {this.initialCondition = initialCondition;}
	
	public String toString() {return initialCondition;}
}
