package com.chrisali.javaflightsim.simulation.setup;

/**
 *	Provides the keys for the integratorConfig EnumMap generated by {@link IntegrationSetup}
 */
public enum IntegratorConfig {
	STARTTIME 	("startTime"),
	DT 	  		("dt"),
	ENDTIME 	("endTime");
	
	private final String integratorConfig;
	
	IntegratorConfig(String integratorConfig) {this.integratorConfig = integratorConfig;}
	
	public String toString() {return integratorConfig;}
}
